TRUNCATE TABLE tbl_country RESTART IDENTITY CASCADE;

INSERT INTO tbl_country (country_name) VALUES
('Iloilo City'),
('Passi City'),
('Ajuy'),
('Alimodian'),
('Anilao'),
('Badiangan'),
('Balasan'),
('Banate'),
('Barotac Nuevo'),
('Barotac Viejo'),
('Batad'),
('Bingawan'),
('Cabatuan'),
('Calinog'),
('Carles'),
('Concepcion'),
('Dingle'),
('Dueñas'),
('Dumangas'),
('Estancia'),
('Guimbal'),
('Igbaras'),
('Janiuay'),
('Lambunao'),
('Leganes'),
('Lemery'),
('Leon'),
('Maasin'),
('Miagao'),
('Mina'),
('New Lucena'),
('Oton'),
('Pavia'),
('Pototan'),
('San Dionisio'),
('San Enrique'),
('San Joaquin'),
('San Miguel'),
('San Rafael'),
('Santa Barbara'),
('Sara'),
('Tigbauan'),
('Tubungan');
